apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
# on the deploy branch, CI replaces "latest" with the commit SHA of the image it just pushed
images:
  - name: ghcr.io/tomasmbrito/house-split
    newTag: latest
