apiVersion: v1
kind: Service
metadata:
  name: house-split
spec:
  # NodePort opens the app on the node; kind maps node port 30080 to localhost:8080
  type: NodePort
  selector:
    app: house-split
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
